#!/usr/bin/env python

from os.path import realpath, dirname, join
import sys

#sys.path.insert(0, join(dirname(realpath(sys.argv[0])), '..', 'src'))

import main


if __name__ == '__main__':
    try:
        main.main(sys.argv)
    except Exception as e:
        print("Exception: "+ '\n' + repr(e))
